apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 3800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: alejandroolmed59/backendbuddy:3.0
        env:
          - name: POSTGRE_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          - name: POSTGRE_HOST
            value: postgres
          - name: POSTGRE_DATABASE
            value: baseSql
          - name: POSTGRE_PORT
            value: '5432'
          - name: POSTGRE_USER
            value: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3800